Description: App deploy template v0.1

Resources:
  Ec2InstanceZoneA:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: t2.micro
      SubnetId: subnet-0b17283f1e058ea64
      SecurityGroupIds:
      - !Ref Ec2SecurityGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo apt update -y
          sudo apt install docker.io -y
          sudo usermod -aG docker $(whoami)
          sudo docker run -d --name container marcotfm/zoologico-ada:latest
    DependsOn: Ec2SecurityGroup

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP and SSH for EC2
      VpcId: vpc-05df277baf4e93b8b
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
