Description: App deploy template v0.1
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  FirstSubnet:
    Type: AWS::EC2::Subnet::Id

Resources:
  Ec2InstanceZoneA:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-051f8a213df8bc089
      InstanceType: t2.micro
      SubnetId: !Ref FirstSubnet
      SecurityGroupIds:
      - !Ref Ec2SecurityGroup
    DependsOn: Ec2SecurityGroup

  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP and SSH for EC2
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0