name: Deploy to AWS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Dockerrun.aws.json
      run: |
        echo '{"AWSEBDockerrunVersion": "1","Image": {"Name": "${{ secrets.AWS_ECR_IMAGE }}:${{ env.DEVELOP_LAST_HASH }}","Update": "true"},"Ports": [{"ContainerPort": 8000}]}' > Dockerrun.aws.json

    - name: Generate new zip
      run: |
        zip -r environment-for-production.zip Dockerrun.aws.json

    - name: terraform init
      run: |
        terraform init \
        -backend-config="bucket=${{ secrets.AWS_S3_BUCKET_NAME }}" \
        -backend-config="key=${{ secrets.AWS_S3_BUCKET_KEY_NAME }}" \
        -backend-config="region=${{ secrets.AWS_REGION }}"

    - name: Apply Terraform
      run: |
        terraform apply

    - name: Update Elastic Beanstalk environment
      run: |
        aws elasticbeanstalk update-environment --environment-name environment-for-production --version-label environment-for-production